#!/usr/bin/python3

import re
import os

dir_path = os.path.dirname(os.path.realpath(__file__))

src_file = open(f'{dir_path}/../iproto-constants.go')
tgt_file = open(f'{dir_path}/../iproto-constants-names.go', mode = 'w')


tgt_file.write('package tarantella\n')
tgt_file.write(f'// generated by {os.path.basename(__file__)}\n')

current_enum = None

enum_re = r'^//\s*enum\s+(\S+)\s*'
constant_re = r'^\s*(?P<name>\S+)\s+(?P<type>\S+) = (?P<value>\S+)\s*$'

for l in src_file.readlines():

    if re.match(enum_re, l):
        if current_enum is not None:
            tgt_file.write('}\n')
        current_enum = re.match(enum_re, l).group(1)
        tgt_file.write('var '+current_enum+' = map[any]string{\n')

    m = re.match(constant_re, l)
    if m:
        tgt_file.write(m.group('type')+'('+m.group('value')+'): "'+m.group('name')+'",\n')


tgt_file.write('}\n')


src_file.close()
tgt_file.close()
